### ISSUE TITLE
setting怎么添加的。没怎么用过vscode。能简单说明一下吗

### ISSUE THREAD

**Issue by fanlushuai** [xuzhongpeng/vscode-note-sync#1]
目前，我如下如所示，写的。没有任何动作应该。

![image](https://user-images.githubusercontent.com/21078607/105109026-9862d280-5af6-11eb-9c60-a0c8c8abff0c.png)

能够劳烦简单说明一下吗？

**Comment by fanlushuai** [comment]
不用说明了。在文档上，添加一个说明吧。我发现，只有重启才会生效那个配置。
也就说，添加完配置需要重新启动一下。
修改配置，比如，关闭。也是需要重启一下。

**Comment by fanlushuai** [comment]
另外，一些关键状态的通知。能设计弹出通知吗？我发现，我打开活动栏，显示的通知嵌入了活动栏里面。字体很小，不容易看。

如果我关闭活动栏（个人为了一点简洁的视觉），什么也收不到了。不清楚，同步是什么状态。

还有一个，是，能够设计 一个延迟提交吗？
我习惯ctrl+s。但是总不能每次都提交吧。
最好设计一个close tab，提交。或者关闭前，运行提交。如果可能的话。

**Comment by fanlushuai** [comment]
还发现，我没有任何改动。也会去git push。
能不能先git status一下。另外git status的时候，注意一下换行符。

**Comment by fanlushuai** [comment]
Note Sync is enabled
Running git -C e:\code\blog pull -f
Already up to date.

初始化的时候，出来这个命令。是不是要把本地强制覆盖。

如果，多地写笔记。未来得及同步。是不是要凉？

**Comment by fanlushuai** [comment]
功能很不错，任重而道远。干巴爹

**Comment by xuzhongpeng** [comment]
1. 对于状态有两种，一种是当前的动作，一种是发生了错误。当前动作放到了左下角的状态栏，发生错误会弹出控制台（不发生错误也会输出到控制台）。不弹框的原因也是想让笔记同步后台无痕运行。如果你需要弹框，再说明下详细原因反馈给我。
2. "noteSync.timeout": 1000 这个能设置提交延迟时间，我个人设置的10000，它是一个节流函数。这样设计的原因是保证每一次写的笔记都能同步到线上。
3. 不设计使用关闭tab、关闭前提交，也是同上原因。因为对于我自己来说，vscode全年无休打开状态，某个tab也可能全天打开，所以不能保证我工作时写的笔记，回家一定能拉取到。如果你需要其它设计，再说明下详细原因反馈给我。
3. 如果未改动，即使`git push`也不会有提交记录
4. `git pull -f`是为了保证笔记一定要下拉到本地，如果冲突了，也要保证本地有。我自己也是在多地使用的，目前没发现凉。而且git上提交记录都有，不怕找不回来。

**Comment by fanlushuai** [comment]
1. 需要弹出窗的原因。简单的一个场景。如果我刚打开笔记。会第一时间触发pull。pull存在十多秒或者更多的等待。那么，我潜意识知道她需要同步，所以，现在我不会去写笔记，我会等待一下。但是如果我不盯着活动栏的状态文字看我就无法获知状态，这种方式相当于，我被阻塞了。弹出框相当于，异步通知的我。（阻塞和非阻塞）

当前，上面所说的场景只是一点，其他位置的状态，也需要推敲一下是否需要。
建议，直接点处理，就是各个关键状态的提醒，都可以通过独立配置，来选择的进行活动栏消息和弹框的方式。

2. 延迟提交这个，和第三个说的，都是关于如何给用户添加更加合适自由的控制提交触发的可选方式。从目前的方式来看，我个人感觉，这个字段不行，首先命名好像不太准，应该是delaytime吧？怎么是timeout。再次，功能也有问题，如果中间我正好把电脑关机了。那么我异地又进行了修改，那么我再次在本地开机打开的时候，直接一个git pull -f ，真的有可能凉，会存在有一个10000ms的周期的文件内容被覆盖的概率。这个字段的加入，只是多了一种选择，还是没有到位。在我看来，还少了一种选择。就是能够让用户有主动触发的能力。其实ctrl+s，或者监听文件修改。有种被胁迫的感觉，因为用户的原本意图，可能并不想立马触发。所以目前这种用户的看似主动方式，并不是真的用户主动。建议，自动提交和ctrl+s解绑一下，和监听修改解绑一下，允许用户来自定义一组快捷键去触发。同时后台有定时器去触发。这样既解决频次，又解决用户的主动需求的刚需。

【4.】 如果未改动，不会有提交记录。这个只是底线，但是不是最合适的情况。git push应该是和服务器有一次交互吧。这种本地可以先判断一下是否需要交互。因为交互是基于网络的，这种成本很高。减少这种交互。举个简单的错误类比
```
if(mysqlClent.query("select id from t_user where username="+usernameA)
==mysqlClent.query("select id from t_user where username="+usernameB)
){
return "这两个人用户id一样"
}

//上面和下面的效果区别，就可以类比一下，这种性质的提交。

if(usernameA==usernameB){
return "两个人id一样";
}
……

```

【5 】git pull -f ，这种太危险了。虽然大多数时候，不会存在问题。但是就算存在覆盖的问题，也很难发现。不知不觉就被骗了。对于笔记这种数据的重要性，这个性质的东西不允许这种东西的存在。这个插件主要价值应该是为了写笔记同步吧。这就显得更加重要了！！建议，还是加条拦截吧。

**Comment by xuzhongpeng** [comment]
1. 弹出框和状态栏，都需要等待同步，都算您说的阻塞，当然只要不造成冲突，您没必要等待同步完成。不用弹框的原因是，我不想让同步这个过程太明显，不管是用有道云笔记还是其它软件也不会在同步完成后弹框提示。**我做这个插件的初衷是我希望同步是无痕的，它不能干扰到我**。如果真的想看状态，那状态栏也应该够用了。
2. 命名确实有误，我会在后续版本中改正。如果按照你说的定时器去触发提交，那这个时间多少算合适，时间较大我觉得不会及时同步（我可能刚写完笔记过会就关机了）；少了，在我全天打开这个编辑器的情况下，它一直触发这个动作我觉得很多余，所以我觉得只有文件更改了才最合适。 关于设置快捷键的情况，我觉得我写了这个插件，就是为了解决它的自动化更新，我不想让它还需要主动来触发。这里只是说我的理解，❗️ **是否需要改动我暂时等待使用的反馈** 
4. 文件没有修改，即使执行git提交命令，也不会跟网络交互，这个建议试一下。
5. `git pull -f`我的理解，就是要让线上的内容强行同步到本地，但是如果内容真的冲突了（比如线上和本地同一个地方改成不一样了），那还是需要手动解决冲突，并不会强行覆盖，对我来说，只要达到这一点就够了。我这样写就是为了减少因为命令带来的手动解决过程，所以即使发生一点错误，我也能接受（git线上会有记录，我随时也能恢复）。如果您确实不想使用`git pull -f`,建议通过`pullCommand`来自定义同步命令。

建议您先试一下功能，后续遇到任何问题，可以在下面继续讨论。

**Comment by fanlushuai** [comment]
【3】功能上，没有修改，确实不会提交。实际执行，根本就没有执行git push，如果没有修改的话。因为 使用了&&符号。自动阻断了。我没有仔细看，我只是发现了git push关键字。单纯git push是一定会网络交互的。所以这点没有问题了。

【2】快捷键绑定ctrl+s，和文本的保存绑定。有好处也有坏处。因为大多数人使用习惯是，写完一点随手保存（但是，并不想提交git）。如果没有自动保存文档的功能。这个是一个问题。举个例子，idea add文件的操作。他会让用户选择，每次add提示或者不提示，直接add。类似这个。核心思想就是用户本地文件的编辑操作，和git操作保持隔离。那么反观，ctrl+s本来是本地文件的操作。现在强绑到了git操作。当然，现有设计思路也没问题。不过存在一部分用户接受不了。

【4，1】两个都是为了当前操作和其他仓库不存在pull的覆盖。如果4能够解决，1的提示也不是问题。同时，无痕的想法，值得肯定。我后续再体验再说。

**Comment by xuzhongpeng** [comment]
好的，谢谢反馈。【1】我还没说清楚，当遇到运行错误的时候，会弹出控制台让用户看到信息。

【2】你说的问题确实存在。如果要达到及时同步，必须要舍弃一些东西，所以git只能把他当做云服务，把git概念弱化。当没有git概念的时候，您一定希望您的写的任何东西，都能及时同步到云服务上。如果这里有更好的思路希望能继续讨论。

1.0.3把您说的`timeout`改成了`delayTime`

**Comment by fanlushuai** [comment]
**git概念 弱化** 很到位！

还是有一点尴尬的事情。就是github workflow也会频繁的被触发，如果workflow采用push触发事件的话。

目前，因为这个逻辑，我不得不放弃push事件来触发workflow。（不管是github免费提供的还是自己的服务器，频繁都是浪费资源。尽管可能资源不怎么值钱，如果biuld博客的话。程序员的快感可能不是加机器，而是优化流程）

剩余的触发事件。手动，定时，web事件。

想要一种**闭环开发思维**（一个地方，编写和控制。流程任务自动完成）。
**在vscode编辑器里**面，既能写博客，又能**随心随时**控制workflow触发（build博客或者其他操作）。

那么想要做到，可能需要一个快捷键绑定web事件的插件功能。

不过，这个功能不是这个插件的责任。但是，也可以看看能不能增加这个特性。哈哈。

**Comment by fanlushuai** [comment]
> **git概念 弱化** 很到位！
> 
> 还是有一点尴尬的事情。就是github workflow也会频繁的被触发，如果workflow采用push触发事件的话。
> 
> 目前，因为这个逻辑，我不得不放弃push事件来触发workflow。（不管是github免费提供的还是自己的服务器，频繁都是浪费资源。尽管可能资源不怎么值钱，如果biuld博客的话。程序员的快感可能不是加机器，而是优化流程）
> 
> 剩余的触发事件。手动，定时，web事件。
> 
> 想要一种**闭环开发思维**（一个地方，编写和控制。流程任务自动完成）。
> **在vscode编辑器里**面，既能写博客，又能**随心随时**控制workflow触发（build博客或者其他操作）。
> 
> 那么想要做到，可能需要一个快捷键绑定web事件的插件功能。
> 
> 不过，这个功能不是这个插件的责任。但是，也可以看看能不能增加这个特性。哈哈。

还有一种方式，就是放弃，这个git弱化的概念。还采用push事件，还是我之前说的，解绑ctrl+s。提供另外的快捷键绑定。

说白了。另外提供一个，自定义快捷键的特性。

用户可以采用git 弱化，但是闭环思维，可能不保（不能让push触发太频繁）。
用户也可以采用自定义的快捷键，自己选择性的提交github，同时采用push事件。（这种方式可能就是，并没有弱化git）

**Comment by fanlushuai** [comment]
找了个插件，专门在vscode上管理workflow的。如果触发机制设置为手动。插件给vscode提供了一个按钮，点击触发。github action官方人员支持，https://github.com/cschleiden/vscode-github-actions

**Comment by xuzhongpeng** [comment]
> **git概念 弱化** 很到位！
> 
> 还是有一点尴尬的事情。就是github workflow也会频繁的被触发，如果workflow采用push触发事件的话。
> 
> 目前，因为这个逻辑，我不得不放弃push事件来触发workflow。（不管是github免费提供的还是自己的服务器，频繁都是浪费资源。尽管可能资源不怎么值钱，如果biuld博客的话。程序员的快感可能不是加机器，而是优化流程）
> 
> 剩余的触发事件。手动，定时，web事件。
> 
> 想要一种**闭环开发思维**（一个地方，编写和控制。流程任务自动完成）。
> **在vscode编辑器里**面，既能写博客，又能**随心随时**控制workflow触发（build博客或者其他操作）。
> 
> 那么想要做到，可能需要一个快捷键绑定web事件的插件功能。
> 
> 不过，这个功能不是这个插件的责任。但是，也可以看看能不能增加这个特性。哈哈。

如果你的目的是同步博客的话，这个插件确实不是很合适，我自己是通过每天启动定时任务来同步的

**Comment by xuzhongpeng** [comment]
> > **git概念 弱化** 很到位！
> > 还是有一点尴尬的事情。就是github workflow也会频繁的被触发，如果workflow采用push触发事件的话。
> > 目前，因为这个逻辑，我不得不放弃push事件来触发workflow。（不管是github免费提供的还是自己的服务器，频繁都是浪费资源。尽管可能资源不怎么值钱，如果biuld博客的话。程序员的快感可能不是加机器，而是优化流程）
> > 剩余的触发事件。手动，定时，web事件。
> > 想要一种**闭环开发思维**（一个地方，编写和控制。流程任务自动完成）。
> > **在vscode编辑器里**面，既能写博客，又能**随心随时**控制workflow触发（build博客或者其他操作）。
> > 那么想要做到，可能需要一个快捷键绑定web事件的插件功能。
> > 不过，这个功能不是这个插件的责任。但是，也可以看看能不能增加这个特性。哈哈。
> 
> 还有一种方式，就是放弃，这个git弱化的概念。还采用push事件，还是我之前说的，解绑ctrl+s。提供另外的快捷键绑定。
> 
> 说白了。另外提供一个，自定义快捷键的特性。
> 
> 用户可以采用git 弱化，但是闭环思维，可能不保（不能让push触发太频繁）。
> 用户也可以采用自定义的快捷键，自己选择性的提交github，同时采用push事件。（这种方式可能就是，并没有弱化git）

这个方式我先加入待办，如果后续还有人反馈的话我会加入这个方式

**Comment by fanlushuai** [comment]
@xuzhongpeng 老哥。最新版本的代码没有提交？能否更新一下？:sweat_smile:
