### ISSUE TITLE
文件更改监听机制不完善

### ISSUE THREAD

**Issue by hazykam** [xuzhongpeng/vscode-note-sync#3]
**描述**：
当文件被 vscode 中的其他插件，或外部编辑器修改时，该同步插件似乎无法及时监听到文件被更改。

**Comment by xuzhongpeng** [comment]
是的，目前监听机制是通过VScode的api，当前还无法脱离VScode的api来进行文件更改的监听

**Comment by hazykam** [comment]
> 是的，目前监听机制是通过VScode的api，当前还无法脱离VScode的api来进行文件更改的监听

我在查阅 vscode 开发文档时，发现 vscode 可以通过创建 `FileSystemWatcher` 来监听文件/文件夹的更改、创建以及删除事件；

在您当前提交的代码中，文件监听似乎是基于 `vscode.workspace.onDidSaveTextDocument` 来实现的，是否可以考虑使用 `FileSystemWatcher` 提供的事件替换当前的实现？

**Comment by xuzhongpeng** [comment]
感谢你的意见，我最近试试

**Comment by xuzhongpeng** [comment]
添加了FileSystemWatcher支持，现在文件更改也会监听到了，提交号[查看这里](https://github.com/xuzhongpeng/vscode-note-sync/commit/9ccd59029232a2c7a58c9a4efdb36e0d512376ba)  VSCode商店看 [版本号1.0.6](https://marketplace.visualstudio.com/items?itemName=JSShou.note-sync)

**Comment by hazykam** [comment]
> 添加了FileSystemWatcher支持，现在文件更改也会监听到了，提交号[查看这里](https://github.com/xuzhongpeng/vscode-note-sync/commit/9ccd59029232a2c7a58c9a4efdb36e0d512376ba) VSCode商店看 [版本号1.0.6](https://marketplace.visualstudio.com/items?itemName=JSShou.note-sync)

您好，我查看了 1.0.6 的变更提交，发现代码中对文件的更改监听仍然使用 workspace 的 `onDidSaveTextDocument` 事件，是漏改了吗？

**Comment by xuzhongpeng** [comment]
> > 添加了FileSystemWatcher支持，现在文件更改也会监听到了，提交号[查看这里](https://github.com/xuzhongpeng/vscode-note-sync/commit/9ccd59029232a2c7a58c9a4efdb36e0d512376ba) VSCode商店看 [版本号1.0.6](https://marketplace.visualstudio.com/items?itemName=JSShou.note-sync)
> 
> 您好，我查看了 1.0.6 的变更提交，发现代码中对文件的更改监听仍然使用 workspace 的 `onDidSaveTextDocument` 事件，是漏改了吗？

是这样的 当前只用了onDidSaveTextDocument的onDidCreate和onDidDelete来监听文件创建和删除，文件的更改依然用的原来的API（原来的API很好，还不清楚新的api会有什么问题）
